when:
  - event: push
    branch: master
  
steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:8.0
    commands:
      - dotnet restore
      - dotnet build --configuration Release --no-restore

  - name: publish
    image: mcr.microsoft.com/dotnet/sdk:8.0
    commands:
      - dotnet pack /p:VersionSuffix=-CI_PIPELINE_NUMBER --configuration Release --no-build --output nupkgs

  - name: push
    image: mcr.microsoft.com/dotnet/sdk:8.0
    commands:
      - dotnet nuget add source https://forgejo.cibbi.duckdns.org/api/packages/cibbi/nuget/index.json --name forgejo
      - dotnet nuget push nupkgs/*.nupkg --source forgejo  --api-key $GITEA_API_KEY
    secrets:
      - GITEA_API_KEY